spring:
 datasource:
   url: jdbc:postgresql://localhost:5432/karol
   username: karol
   password: password
   driver-class-name: org.postgresql.Driver
 jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
