spring:
 datasource:
   url: jdbc:postgresql://localhost:5433/conhub
   username: postgres
   password: password
   driver-class-name: org.postgresql.Driver
 jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
